services:
  app-backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: app-backend
    ports:
      - "${APP_PORT}:${APP_PORT}"
    command: "uvicorn --factory app.core.main:create_app --reload --host ${APP_HOST} --port ${APP_PORT}"
    environment:
      - OLLAMA_HOST=${OLLAMA_HOST}
    env_file:
      - ../.env
    volumes:
      - ../:/app/

  s3:
    image: minio/minio:latest
    container_name: s3_minio
    restart: unless-stopped
    ports:
      - "${MINIO_PORT}:${MINIO_PORT}"
      - "${MINIO_ADMIN_PORT}:${MINIO_ADMIN_PORT}"
    command: server /s3_data --console-address ":${MINIO_ADMIN_PORT}"
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    env_file:
      - ../.env
    volumes:
      - s3_data:/s3_data
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  s3_data: